# Use a imagem Python como base
FROM python:3.8

# Copie o arquivo do servidor para o contêiner
COPY server.py /app/server.py

# Defina o diretório de trabalho
WORKDIR /app

# Execute o servidor Python
CMD ["python", "server.py"]
